config/routes.rb
Breezyboats::Application.routes.draw do
  resources :contacts

	root :to => 'welcome#index'

	devise_for :admin_users, ActiveAdmin::Devise.config
	ActiveAdmin.routes(self)

	resources :boats

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/boat.rb
class Boat < ActiveRecord::Base
	has_many :photos
	has_many :contacts
	belongs_to :category

	SHIP_TYPES = [
		["Boats", "Boats"],
		["Manitou Pontoons", "MAnitou Pontoons"],
		["Pontoons", "Pontoons"],
		["Sail Boats", "Sail Boats"],
		["Trailers", "Trailers"],
	]

	has_attached_file :main_image, :styles => { :large => "554x360>", :medium => "300x230>", :small => "90x58>" }
	validates_attachment_size :main_image, :less_than => 100.megabytes


  attr_accessible :beam, :description, :engine,
  								:engine_hours, :hull_construction, :length,
  								:name, :price, :weight, :year, :type_string, :main_image, :category_id,
  								:brand, :model, :is_sold, :reduced_price

  def to_s
  	"#{id}, #{brand}, #{model}"
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :boats
  attr_accessible :description, :name, :slug
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  belongs_to :boat
  attr_accessible :email, :email_subject, :message, :name, :phone, :boat, :boat_id
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :pic, :boat, :boat_id
  belongs_to :boat
  has_attached_file :pic, :styles => { :large => "554x360>", :medium => "300x230>", :small => "90x58>" }
  validates_attachment_size :pic, :less_than => 100.megabytes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
  layout "application"
  # GET /boats
  # GET /boats.json
  def index
    @boats = Boat.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boats }
    end
  end

  # GET /boats/1
  # GET /boats/1.json
  def show
    @boat = Boat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @boat }
    end
  end

  # GET /boats/new
  # GET /boats/new.json
  def new
    @boat = Boat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @boat }
    end
  end

  # GET /boats/1/edit
  def edit
    @boat = Boat.find(params[:id])
  end

  # POST /boats
  # POST /boats.json
  def create
    @boat = Boat.new(params[:boat])

    respond_to do |format|
      if @boat.save
        format.html { redirect_to @boat, notice: 'Boat was successfully created.' }
        format.json { render json: @boat, status: :created, location: @boat }
      else
        format.html { render action: "new" }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boats/1
  # PUT /boats/1.json
  def update
    @boat = Boat.find(params[:id])

    respond_to do |format|
      if @boat.update_attributes(params[:boat])
        format.html { redirect_to @boat, notice: 'Boat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @boat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @boat = Boat.find(params[:id])
    @boat.destroy

    respond_to do |format|
      format.html { redirect_to boats_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < InheritedResources::Base
	def index
		if params[:boat_id]
			@boat = Boat.find_by_id(params[:boat_id])
		end
	end

	def create
		if params[:contact][:boat]
			params[:contact][:boat] = Boat.find_by_id(params[:contact][:boat])
		end

		# Clean the fucking strings. SPam everywhere ill formatted
    new_message = params[:message].encode("ISO-8859-1", :invalid => :replace)
		new_message = new_message.encode("UTF-8")
		params[:message] = new_message

		# Store it and shit
		@contact = Contact.new(params[:contact])

		if @contact.save
			redirect_to(root_path, :notice => "Thank you for you inquiry. We'll contact you shortly")
		else
			render :action => "index"
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
	def prepare_type_string(type_string)
		new_string = type_string.downcase.tr(' ', '_')
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/boats/_form.html.erb
<%= form_for(@boat) do |f| %>
  <% if @boat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boat.errors.count, "error") %> prohibited this boat from being saved:</h2>

      <ul>
      <% @boat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="field">
    <%= f.label :beam %><br />
    <%= f.number_field :beam %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.number_field :weight %>
  </div>
  <div class="field">
    <%= f.label :engine %><br />
    <%= f.text_field :engine %>
  </div>
  <div class="field">
    <%= f.label :engine_hours %><br />
    <%= f.number_field :engine_hours %>
  </div>
  <div class="field">
    <%= f.label :hull_construction %><br />
    <%= f.text_field :hull_construction %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boats/edit.html.erb
<h1>Editing boat</h1>

<%= render 'form' %>

<%= link_to 'Show', @boat %> |
<%= link_to 'Back', boats_path %>

app/views/boats/index.html.erb
<section id="headline2">
	<div class="container">
		<h3>Current Inventory</h3>
	</div>
</section>
<div class="white-space"></div>

<section class="container page-content" >
	<nav class="primary clearfix">

		<ul>
			<li><a href="#" class="selected" data-filter="*">All</a></li>
			<% for category in Category.all %>
				<li>
					<a class="" href="#" data-filter=".<%= category.slug %>"><%= category.name %></a>
				</li>
			<% end %>
		</ul>
	</nav>

	<div  class="portfolio">
<% for boat in @boats %>
		<div class="portfolio-item four columns entry <%= boat.category.slug %> -item">
			<a class="Single-Item"  href="<%= boat.main_image.url(:large) %>">
				<%= image_tag boat.main_image.url(:medium) %>

				<% if boat.is_sold %>
					<%= image_tag image_path("sold.png"), :id => "sold-overlay" %>
				<% end %>
				<span class="prt-img-hov-bg"></span>
			</a>
			<a href="<%= boat_url(boat) %>">
				<h5> <%= boat.brand %> </h5>
				<em> <%= boat.model %> </em>
			</a>
		</div>
<% end %>

	</div><!-- end-portfolio -->


	<div class="sixteen columns">
		<hr>
	</div>
<!-- 	<div class="pagination2 pagination2-centered">
		<ul>
			<li class="disabled"><a href="#">&laquo;</a></li>
			<li class="active"><a href="#">1</a></li>
			<li><a href="#">2</a></li>
			<li><a href="#">3</a></li>
			<li><a href="#">4</a></li>
			<li><a href="#">&raquo;</a></li>
		</ul>
	</div> -->
	<div class="white-space"></div>

</section><!-- container -->

app/views/boats/new.html.erb
<h1>New boat</h1>

<%= render 'form' %>

<%= link_to 'Back', boats_path %>

app/views/boats/show.html.erb
<section id="headline2">
  <div class="container">

  </div>
</section>

<section class="container page-content" >

  <div class="six columns">
    <%= image_tag @boat.main_image.url(:large), :id => "big-image-canvas" %>
    <% if @boat.is_sold %>
        <%= image_tag image_path("sold.png"), :id => "sold-overlay" %>
    <% end %>
  <% @boat.photos.each do |photo| %>
    <%= image_tag photo.pic.url(:large), :class => "thumbnail-click", :width => "90", :height => "90" %>
  <% end %>
  </div>
  <div class="nine columns" >

    <h5 class="helvetic5"><%= @boat.brand %></h5>
    <h4><%= @boat.model %></h4>
    <p><%= @boat.description %></p>
    <p><strong>Length Overall: </strong><%= @boat.length %></p>
    <p><strong>Beam: </strong><%= @boat.beam %></p>
    <p><strong>Weight: </strong> <%= @boat.weight %> lbs.</p>
    <p><strong>Engine: </strong><%= @boat.engine %></p>
    <p><strong>Engine Hours: </strong><%= @boat.engine_hours %></p>
    <p><strong>Hull Construction: </strong><%= @boat.hull_construction %></p>


    <a href="<%= contacts_path %>?boat_id=<%= @boat.id %>" class="magicmore">Price: <%= @boat.price %></a>

  </div>

  <div class="clear"></div>
  <p>&nbsp;</p>

  <br class="clear" /><p>&nbsp;</p>

</section><!-- container -->

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :boat %><br />
    <%= f.text_field :boat %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :email_subject %><br />
    <%= f.text_field :email_subject %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Boat:</b>
  <%= @contact.boat %>
</p>

<p>
  <b>Name:</b>
  <%= @contact.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact.email %>
</p>

<p>
  <b>Email subject:</b>
  <%= @contact.email_subject %>
</p>

<p>
  <b>Message:</b>
  <%= @contact.message %>
</p>

<p>
  <b>Phone:</b>
  <%= @contact.phone %>
</p>


<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Breezy Boat City</title>

  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>

  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700,900|Oswald:300,400' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

  <div id="wrap">
    <section id="top-head">
      <div class="container">
        <!-- <div class="top-links"><img src="images/ico-ad04.png" alt=""> <a href="#">Form</a> | <a href="#">Terms</a> | <a href="#">Contact</a></div> -->
        <div class="top-social">
          <a href="https://www.facebook.com/pages/Breezy-Boat-City/227092020636374">
            <%= image_tag "social-icons/facebook.png" %>
          </a>
          <a href="#">
            <%= image_tag "social-icons/twitter.png" %>
          </a>
          <a href="#">
            <%= image_tag "social-icons/youtube.png" %>
          </a>
          <a href="#">
            <%= image_tag "social-icons/linkedin.png" %>
          </a>
          <a href="#">
            <%= image_tag "social-icons/rss.png" %>
          </a>
        </div>
      </div>
    </section>
    <header id="header" class="container">
      <div class="four columns logo">
        <a href="<%= root_path %>">
          <%= image_tag "logo.png" %>
        </a>
        <br />
      </div>
      <nav id="nav-wrap" class="twelve columns">
        <ul id="nav">
          <li class="current">
            <a data-description="All Start here" href="<%= root_path %>">Home</a>
          </li>
          <li>
            <a data-description="Current Inventory" href="<%= boats_path %>">Our Boats</a>
            <ul>
              <li><a href="<%= boats_path %>">Manitou Pontoons</a></li>
              <li><a href="<%= boats_path %>">Used Boats</a></li>
              <li><a href="<%= boats_path %>">Sailboats</a></li>
              <li><a href="<%= boats_path %>">Paddleboards</a></li>
              <li><a href="<%= boats_path %>">Trailers</a></li>
              <li><a href="<%= boats_path %>">Boat Products</a></li>
            </ul>
          </li>
          <li><a data-description="What We Do"  href="<%= page_path('services') %>">Services</a>
            <ul>
              <li><a href="<%= page_path('services') %>">Boat & Engine Repair</a></li>
              <li><a href="<%= page_path('services') %>">Trailer Repair</a></li>
              <li><a href="<%= page_path('services') %>">Boat Storage</a></li>
              <li><a href="<%= page_path('services') %>">Boast Detailing</a></li>

            </ul>
          </li>
          <li><a data-description="Who Are We"  href="<%= page_path('about') %>">About</a></li>

          <li><a data-description="Get In Touch"  href="<%= contacts_path %>">Contact</a>

          </li>
        </ul>
      </nav>
      <!-- /nav-wrap -->
      <p>&nbsp;</p>
    </header><!-- end-header -->
    <%= yield %>
  </div>

 <!--  <section class="container" >
  </section> -->


  <footer id="footer">
    <div class="container footer-in">
      <div class="disclaimer four columns">
        <h4 class="subtitle">Disclaimer</h4>
        <br />
        <p>Information presented on this website is collected, maintained, and provided for the convenience of the user. While every effort is made to keep such information accurate and up-to-date. Under no circumstances will Breezy Boat City be liable for any actions taken or omissions made from reliance on any information contained herein from whatever source nor will Breezy Boats City be liable for any other consequences from any such reliance.
        </p>
        <br />
        <div class="copyright-txt">&nbsp; © 2013. All Rights Reserved.<br>
          <a href="#" class="terms">Terms of Service</a> | <a href="#" class="terms">Privacy Policy</a></div>
        </div><!-- Disclaimer -->


        <div class="four columns">
          <h4 class="subtitle">stay connected</h4>
          <br />
          <p class="twitt-txt">@<a href="https://twitter.com/breezyboatcity">breezyboatcity</a>
            <span id="twitter"></span>
          </p>
          <div class="socailfollow">
            <a href="#" class="facebook">
              <%= image_tag "social_facebook2.png" %>
            </a>
            <a href="#" class="twitter">
              <%= image_tag "social_twitter2.png" %>
            </a>
            <a href="#" class="dribble">
              <%= image_tag "social_dribble.png" %>
            </a>
            <a href="#" class="pinterest">
              <%= image_tag "social_pinterest.png" %>
            </a>
            <a href="#" class="vimeo">
              <%= image_tag "social_vimeo.png" %>
            </a>
            <a href="#" class="youtube">
              <%= image_tag "social_youtube.png" %>
            </a>
          </div>
        </div><!-- end-follow2 -->



        <div class="four columns">
          <h4 class="subtitle">Contact Information</h4>
          <br />
          <p>
            <%= image_tag "social_address.png" %>
            &nbsp;<strong>Address:</strong>
            <br />
            2816 Gulf Breeze Parkway Gulf Breeze, FL 32563
          </p>

          <p>
            <%= image_tag "social_phone.png" %>
            &nbsp;<strong>Phone:</strong>
            <br />
            + 1 (850) 934 6010<br />
          </p>

          <p>
            <%= image_tag "social_mail.png" %>
            &nbsp;<strong>Email:</strong>
            <br />
            jan@breezyboatcity.com<br />
          </p>
        </div><!-- end-contact2 -->
      </div><!-- end-footer-in -->
      <div class="footbot" >
        <div class="footer-navi">
          <a href="#">Home</a> | <a href="#">Boats</a> | <a href="#">Services</a> | <a href="#">About</a> | <a href="#">Contact</a>
        </div>
        <%= image_tag "logo-footer.png" %>
      </div><!-- end-footbot -->
    </footer>
    <!-- end-footer -->
    <span id="scroll-top"><a class="scrollup"></a></span>
  </div><!-- end-wrap -->
</body>
</html>

app/views/pages/services.html.erb
<section id="headline2">
	<div class="container">
		<h3>Services</h3>
	</div>
</section>

<section class="container page-content" >

	<p>&nbsp;</p>
	<div class="row">
		<div class="eleven columns">

			<h1><strong>You name it, we do it! The weather's warming up, let us know how we can help.</strong></h1>
			<h4>We offer a variety of services for you to take advantage of. As always these services come with the highest level of customer service and quality you can expect from Breezy Boat City.</h4>

		</div>

	</div>
	<br class="clear">
	<p>&nbsp;</p>
	<div class="sixteen columns">
		<div class="title">
			<h4>major services</h4>
		</div>
	</div>
	<p>&nbsp;</p>
	<br class="clear">

	<div class="columns pad-l10">
		<div class="three columns serv-big-pic pad-l20">
			<img src="<%= image_path 'services-pic2.jpg' %>" alt=""><br>
			<h4><strong>Boat & Engine Repair</strong></h4>
			<p>Our experienced mechanics are ready to diagnose and repair any problems you may have. We can take care of normal scheduled maintenance or more in depth jobs. Our labor rates are the lowest in town. <br></p>
		</div>
	</div>
	<div class="columns pad-l10">
		<div class="three columns serv-big-pic pad-l20">
			<img src="<%= image_path 'services-pic1.jpg' %>" alt=""><br>
			<h4><strong>Trailer Repair</strong></h4>
			<p>Our experienced mechanics can provide a free trailer inspection including rolling gear and lights.  We provide a quick turn-around of services depending upon your needs.  We have gantry supports for safe removal and return of your boats on and off of your trailer. <br></p>
		</div>
	</div>
	<div class="columns pad-l10">
		<div class="three columns serv-big-pic pad-l20">
			<img src="<%= image_path 'services-pic3.jpg' %>" alt=""><br>
			<h4><strong>Boat Storage</strong></h4>
			<p>We have ample, safe, and secure storage for your boats and trailers.  As the seasons come and go, you can store your boat and/or trailer. Entry is controlled, and it is always lighted and safe. Discounts are available!<br><strong>Prices Start at $55.00</strong> </p>
		</div>
	</div>
	<div class="columns pad-l10">
		<div class="three columns serv-big-pic pad-l20">
			<img src="<%= image_path 'services-pic4.jpg' %>" alt=""><br>
			<h4><strong>Boat Detailing</strong></h4>
			<p>We will professionally clean your boat to your satisfaction. You will not find a better deal in the Gulf Breeze or Pensacola area. We use the safest marine products on the market to ensure the highest quality of work. <br></p>
		</div>
	</div>




	<div class="white-space"></div>

															</section><!-- container -->

app/views/welcome/index.html.erb
    <section id="hero" class="tbg1">

      <div id="layerslider-container-fw">

        <div id="layerslider" style="width: 100%; height: 461px; margin: 0px auto; ">

          <div class="ls-layer" style="slidedirection: top; slidedelay: 12000; durationin: 1500; durationout: 1500; delayout: 500;">
            <%= image_tag "hero-pic-home1.jpg", :class => "ls-bg" %>

            <h1 class="ls-s3" style="position: absolute; top:180px; left: 23%; slidedirection : bottom; slideoutdirection : left; durationin : 3000; durationout : 750; easingin : easeInOutQuint; easingout : easeInBack; delayin : 1000;">Great things for boating</h1>
            <h3 class="ls-s3 l1-s1" style="position: absolute; top:240px; left: 33%; slidedirection : bottom; slideoutdirection : left; durationin : 3000; durationout : 750; easingin : easeInOutQuint; easingout : easeInBack; delayin : 1000;">There is no better time to buy a boat and start enjoying countless adventures.  No matter if it is fishing or family fun we can get you started.</h3>

          </div>

          <div class="ls-layer" style="slidedirection: right; slidedelay: 7000; durationin: 1500; durationout: 1500;">
            <%= image_tag "hero-pic-home2.jpg", :class => "ls-bg" %>

            <h1 class="ls-s1 l2-s1" style="position: absolute; top:190px; left: 0; slidedirection : fade; slideoutdirection : bottom; durationin : 1500; durationout : 750; easingin : easeInOutQuint; easingout : easeInOutQuint; delayin : 1500;">Manitou</h1>
            <h3 class="ls-s2 l2-s1" style="position: absolute; top:280px; left: 0; slidedirection : fade; slideoutdirection : bottom; durationin : 1500; durationout : 750; easingin : easeInOutQuint; easingout : easeInOutQuint; delayin : 1000;">Pontoon Boats</h3>
            <h3 class="ls-s3 l2-s1" style="position: absolute; top:332px; left: 0; slidedirection : fade; slideoutdirection : bottom; durationin : 1500; durationout : 750; easingin : easeInOutQuint; easingout : easeInOutQuint; delayin : 1500;">Manitou has changed the way pontoon boats should look on the water.</h3>
          </div>

          <div class="ls-layer" style="slidedirection: top; slidedelay: 7000; durationin: 1500; durationout: 1500; delayout: 500;">
            <%= image_tag "hero-pic-home3.jpg", :class => "ls-bg" %>

            <h1 class="ls-s1 l3-s1" style="position: absolute; top:224px; color:#63a405; left: 29%;slidedirection : fade; slideoutdirection : bottom; durationin : 1500; durationout : 750; easingin : easeInOutQuint; easingout : easeInOutQuint; delayin : 1500;">Breezy Boat City</h1>
            <h3 class="ls-s2 l3-s1" style="position: absolute; top:300px; left: 29%; color:#000; slidedirection : bottom; slideoutdirection : top; durationin : 750; durationout : 750; easingin : easeOutBack; easingout : easeInBack; delayin : 1000;">No matter what or when.  It is time to be back on the water!</h3>
          </div>
        </div>
      </div>
      <div class="blox dark bluebox">
        <div class="container alignleft">
          <br>
          <div class="five columns v-shadow-l pad-r20">
            <h3>
              <strong>Welcome!</strong> <br />
              <small>Great things for boating...</small>
            </h3>
            <br />
            <p>
              At Breezy Boat City we  provide friendly, professional service for boaters.  We want to help you sell a boat, buy a boat, store a boat, service your boat or assist with any other unique boating needs.
            </p>
            <hr>
            <%= image_tag "p-vw2.png" %>
          </div>
          <div class="eleven columns alpha omega">
            <div class="row">
              <div class="five columns">
                <div class="columns magic">
                  <%= image_tag "s-h-ico1.png" %>
                  <h4>Consignments</h4>
                  <p>Nearly 50,000 pass our consignment lot each day. That means nearly 50,000 sales opportunities each day.
                  </p>
                  <a href="<%= boats_path %>" class="magicmore">Learn more</a>
                </div>
              </div>
              <div class="five columns">
                <div class="columns magic">
                  <%= image_tag "s-h-ico2.png" %>
                  <h4>Detailing</h4>
                  <p>Breezy Boat City specializes in taking oxidized boats and RV's and returning them to their original shine!
                  </p>
                  <a href="<%= page_path('services') %>" class="magicmore">Learn more</a>
                </div>
              </div>
            </div>
            <p>&nbsp;</p>
            <br class="clear">
            <div class="row">

              <div class="five columns">
                <div class="columns magic">
                  <%= image_tag "s-h-ico3.png" %>
                  <h4>Services</h4>
                  <p>We offer a variety of services for you to take advantage of. As always these services come with the highest level of customer service and quality you can expect from Breezy Boat City.
                  </p>
                  <a href="<%= page_path('services') %>" class="magicmore">Learn more</a>
                </div>
              </div>
              <div class="five columns">
                <div class="columns magic">
                  <%= image_tag "s-h-ico4.png" %>
                  <h4>Storage</h4>
                  <p>We have ample, safe, and secure storage for your boats and trailers.  As the seasons come and go, you can store your boat and/or trailer. Entry is controlled, and it is always lighted and safe.
                  </p>
                  <a href="<%= page_path('services') %>" class="magicmore">Learn more</a>
                </div>
              </div>

            </div>

          </div>

        </div>
      </div>
    </section><!-- end-hero-->

    <section class="container home-content" >
      <p>&nbsp;</p>
      <div class="container column">
        <div class="promobox">
          <div class="row">
            <div class="eleven columns">
              <br>
              <h3>
                <strong>Our Professional Staff Is Ready To Help You!</strong>
              </h3>

              <p>
                We are providing a one stop shopping location for “great things for boats...” The company specializes in consignment sales, dry storage and trailer repair, but offers a variety of services that includes refurbishment, detailing and marine consulting.
              </p>

            </div>
            <div class="four columns omega">
              <p>&nbsp;</p>
              <div class="magic-link alignright">
                <a class="get shadow1" href="<%= contacts_path %>">Contact us today!</a><br class="clear" />
              </div>
            </div>
          </div>
        </div>
      </div>
      <p>&nbsp;</p>

      <br class="clear" /><p>&nbsp;</p>
    </section>